var gulp = require('gulp');
var concat = require('gulp-concat');
var sass = require('gulp-sass');
var inject = require('gulp-inject-string');

var paths = {
  sass: ['./scss/**/*.scss'],
  controllers: ['./js/controllers/*.js']
};

gulp.task('controllers', function () {
  return gulp.src('./js/controllers/*.js')
      .pipe(concat('controllers.js'))
      .pipe(inject.prepend('// DO NOT EDIT\n// Auto generated by gulp task "controllers"\n'))
      .pipe(gulp.dest('./js/'))
});

gulp.task('watch', function() {
  gulp.watch(paths.controllers, ['controllers']);
});